apiVersion: v2
name: seldon-core
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "2.40.0"

dependencies:
  - name: seldon-core-v2-crds
    repository: file://subcharts/seldon-core-v2-crds
    version: ^0
    condition: seldon-core-v2-crds.enabled

  - name: seldon-core-v2-kafka
    repository: file://subcharts/seldon-core-v2-kafka
    version: ^0
    condition: seldon-core-v2-kafka.enabled

  - name: seldon-core-v2-servers
    repository: https://seldonio.github.io/helm-charts
    version: ^0
    condition: seldon-core-v2-servers.enabled

  - name: seldon-core-v2-setup
    repository: https://seldonio.github.io/helm-charts
    version: ^0
    condition: seldon-core-v2-setup.enabled

  - name: strimzi-kafka-operator
    repository: https://strimzi.io/charts/
    version: ^0
    condition: strimzi-kafka-operator.enabled
