# Default values for seldon-core.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

seldon-core-v2-crds:
  enabled: true
  model:
    enabled: true
  server:
    enabled: true
  serverConfig:
    enabled: true
  experiment:
    enabled: true
  pipeline:
    enabled: false

seldon-core-v2-servers:
  enabled: true
  mlserver:
    replicas: 1
  triton:
    replicas: 1

seldon-core-v2-setup:
  enabled: true

seldon-core-v2-kafka:
  enabled: false

strimzi-kafka-operator:
  enabled: false
  featureGates: "+UseKRaft,+UseStrimziPodSets"
