apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: seldon-core-v2
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:arenaml/argocd-apps
    path: system/seldon-core-v2
    helm:
      releaseName: seldon-core-v2
  destination:
    server: "https://kubernetes.default.svc"
    namespace: seldon-mesh
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
