apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: seldon-core-v2
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://seldonio.github.io/helm-charts
    chart: seldon-core-v2-setup
    targetRevision: "*"
    helm:
      releaseName: seldon-core-v2
  destination:
    server: "https://kubernetes.default.svc"
    namespace: seldon-mesh
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
