apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: arena-landing-page-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: arena-landing-page-service
                port:
                  number: 3000
